language: csharp
solution: StardewConfigFramework.sln
install:
  - nuget restore StardewConfigFramework.sln
  - nuget install NUnit.Console -Version 3.8.0 -OutputDirectory $EXTRACT_PATH/testrunner
script:
  - mkdir $EXTRACT_PATH
  - curl -L $SMAPI_DOWNLOAD_URL -o $EXTRACT_PATH/smapi.zip
  - unzip $EXTRACT_PATH/smapi.zip -d $EXTRACT_PATH
  - msbuild /p:Configuration=Release /p:ExplicitSMAPIPath="$SMAPI_FOLDER" StardewConfigFramework.sln
  - mono $EXTRACT_PATH/testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./StardewConfigFrameworkTests/bin/Release/StardewConfigFrameworkTests.dll
